import { Story, Category, Author } from './types';

const authors: Author[] = [
  {
    id: '1',
    name: 'Sarah Blackwell',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop',
    bio: 'Investigative journalist specializing in cold cases and unsolved mysteries.',
  },
  {
    id: '2',
    name: 'Marcus Chen',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop',
    bio: 'True crime author and former forensic analyst.',
  },
  {
    id: '3',
    name: 'Elena Vasquez',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop',
    bio: 'Criminal psychology researcher and documentary filmmaker.',
  },
];

export const categories: Category[] = [
  {
    id: '1',
    slug: 'serial-killers',
    name: 'Serial Killers',
    description: 'In-depth profiles and investigations into the minds of serial killers.',
    image: 'https://images.unsplash.com/photo-1509248961406-689e1e7de57d?w=800&h=600&fit=crop',
    storyCount: 4,
  },
  {
    id: '2',
    slug: 'cold-cases',
    name: 'Cold Cases',
    description: 'Unsolved cases that continue to haunt investigators decades later.',
    image: 'https://images.unsplash.com/photo-1453873531674-2151bcd01707?w=800&h=600&fit=crop',
    storyCount: 3,
  },
  {
    id: '3',
    slug: 'disappearances',
    name: 'Disappearances',
    description: 'People who vanished without a trace, leaving only questions behind.',
    image: 'https://images.unsplash.com/photo-1516557070061-c3d1653fa646?w=800&h=600&fit=crop',
    storyCount: 2,
  },
  {
    id: '4',
    slug: 'historical-crimes',
    name: 'Historical Crimes',
    description: 'Infamous criminal cases that shaped history and law enforcement.',
    image: 'https://images.unsplash.com/photo-1461360228754-6e81c478b882?w=800&h=600&fit=crop',
    storyCount: 2,
  },
  {
    id: '5',
    slug: 'unsolved-mysteries',
    name: 'Unsolved Mysteries',
    description: 'Baffling cases that defy explanation and remain open.',
    image: 'https://images.unsplash.com/photo-1478760329108-5c3ed9d495a0?w=800&h=600&fit=crop',
    storyCount: 2,
  },
  {
    id: '6',
    slug: 'strange-events',
    name: 'Strange Events',
    description: 'Bizarre and unexplained occurrences from around the world.',
    image: 'https://images.unsplash.com/photo-1504701954957-2010ec3bcec1?w=800&h=600&fit=crop',
    storyCount: 1,
  },
];

export const stories: Story[] = [
  {
    id: '1',
    slug: 'the-night-stalker-reign-of-terror',
    title: 'The Night Stalker: A City Held Hostage by Fear',
    excerpt: 'How Richard Ramirez terrorized Los Angeles during the summer of 1985, leaving a trail of horror that paralyzed an entire city.',
    content: `<p>In the sweltering summer of 1985, Los Angeles was gripped by a terror unlike anything the city had ever known. A shadowy figure was entering homes at night, committing unspeakable acts of violence against the residents inside.</p>
<p>The attacker showed no pattern in choosing victims — men, women, the elderly, couples — anyone could be next. The only constant was the darkness. He always struck at night, earning him the chilling moniker that would become infamous: The Night Stalker.</p>
<p>Richard Ramirez, a drifter from El Paso, Texas, had arrived in Los Angeles with a history of petty crime and drug abuse. But what unfolded over the course of that summer went far beyond anything in his past. Between June and August 1985, Ramirez committed at least 13 murders and numerous other violent crimes.</p>
<p>The city was paralyzed. Hardware stores sold out of locks and security systems. Residents slept with loaded firearms beside their beds. The fear was palpable — a collective dread that seeped into every neighborhood from the San Fernando Valley to the coast.</p>
<p>What made the Night Stalker case particularly terrifying was the randomness of it all. There was no victim profile, no geographic pattern that detectives could use to predict the next attack. Ramirez moved like a ghost through the suburban sprawl, selecting homes seemingly at random.</p>`,
    image: 'https://images.unsplash.com/photo-1478760329108-5c3ed9d495a0?w=1200&h=800&fit=crop',
    category: categories[0],
    author: authors[0],
    publishedAt: '2024-01-15',
    readingTime: 12,
    featured: true,
    trending: true,
    tags: ['serial-killer', 'los-angeles', '1980s'],
  },
  {
    id: '2',
    slug: 'zodiac-cipher-remains-unbroken',
    title: 'The Zodiac Killer: Ciphers, Clues, and a Century of Silence',
    excerpt: 'Over fifty years later, the Zodiac Killer remains one of America\'s most elusive criminals. His cryptic messages still taunt investigators.',
    content: `<p>The letter arrived at the San Francisco Chronicle on August 1, 1969. It began simply enough: "Dear Editor, This is the murderer of the 2 teenagers last Christmas at Lake Herman." What followed was a demand that would captivate and terrify the nation for decades.</p>
<p>The Zodiac Killer, as he called himself, wasn't content merely to kill. He wanted to play games. He sent cryptograms to newspapers, daring the public to decode them. He taunted police with letters dripping with arrogance and menace. He claimed to have killed 37 people, though investigators have only confirmed five deaths and two survivors.</p>
<p>The case remains one of the most investigated unsolved crimes in American history. Thousands of suspects have been examined, DNA evidence has been analyzed with cutting-edge technology, and amateur detectives continue to pore over the Zodiac's ciphers.</p>`,
    image: 'https://images.unsplash.com/photo-1509248961406-689e1e7de57d?w=1200&h=800&fit=crop',
    category: categories[0],
    author: authors[1],
    publishedAt: '2024-02-03',
    readingTime: 15,
    featured: false,
    trending: true,
    tags: ['zodiac', 'san-francisco', 'cipher', 'unsolved'],
  },
  {
    id: '3',
    slug: 'black-dahlia-hollywoods-darkest-secret',
    title: 'The Black Dahlia: Hollywood\'s Darkest Unsolved Murder',
    excerpt: 'The brutal 1947 murder of Elizabeth Short remains Los Angeles\' most infamous unsolved case, a grim tale of broken dreams and darkness.',
    content: `<p>On the morning of January 15, 1947, a mother walking with her young daughter along a vacant lot in Leimert Park, Los Angeles, noticed what she thought was a broken department store mannequin lying in the grass. As she moved closer, the horrifying truth became clear.</p>
<p>The body of Elizabeth Short, 22, had been found — bisected at the waist, drained of blood, and posed with her arms raised above her head. The murder was so grotesque, so theatrical in its cruelty, that it immediately captured the attention of a city already fascinated by the darker side of glamour.</p>
<p>Short had come to Hollywood like so many young women of her generation, chasing the dream of stardom. She was beautiful, ambitious, and utterly unknown before her death made her the most famous murder victim in Los Angeles history.</p>`,
    image: 'https://images.unsplash.com/photo-1453873531674-2151bcd01707?w=1200&h=800&fit=crop',
    category: categories[1],
    author: authors[2],
    publishedAt: '2024-02-20',
    readingTime: 10,
    featured: false,
    trending: true,
    tags: ['black-dahlia', 'hollywood', '1947', 'unsolved'],
  },
  {
    id: '4',
    slug: 'vanishing-of-flight-mh370',
    title: 'Into Thin Air: The Disappearance of Flight MH370',
    excerpt: 'A Boeing 777 with 239 souls aboard vanished from radar in 2014. A decade later, the mystery endures.',
    content: `<p>At 12:41 AM on March 8, 2014, Malaysia Airlines Flight MH370 departed Kuala Lumpur International Airport bound for Beijing. On board were 227 passengers and 12 crew members. The Boeing 777-200ER, one of the safest aircraft ever built, was expected to land at 6:30 AM.</p>
<p>It never arrived. Somewhere over the South China Sea, the aircraft deviated from its planned route. Its transponder was switched off. Military radar tracked it turning west, crossing back over the Malay Peninsula, and heading out over the Indian Ocean. Then it vanished.</p>
<p>What followed was the largest and most expensive search operation in aviation history, covering millions of square kilometers of ocean floor. Despite years of searching, only scattered pieces of debris have been found washed up on beaches around the Indian Ocean.</p>`,
    image: 'https://images.unsplash.com/photo-1516557070061-c3d1653fa646?w=1200&h=800&fit=crop',
    category: categories[2],
    author: authors[0],
    publishedAt: '2024-03-08',
    readingTime: 14,
    featured: true,
    trending: false,
    tags: ['mh370', 'aviation', 'disappearance'],
  },
  {
    id: '5',
    slug: 'jack-the-ripper-whitechapel-mystery',
    title: 'Jack the Ripper: The Whitechapel Terror That Defined Crime',
    excerpt: 'In the fog-shrouded streets of 1888 London, a killer stalked the night. His identity remains history\'s greatest criminal mystery.',
    content: `<p>The autumn of 1888 transformed London's East End into a landscape of dread. In the narrow, gaslit streets of Whitechapel, a killer was at work — methodical, brutal, and utterly invisible to the largest police force in the world.</p>
<p>Between August and November of that year, at least five women were murdered in a manner so savage that it shocked even the hardened residents of Victorian London's most impoverished district. The killer, who would come to be known as Jack the Ripper, displayed a surgical precision that led investigators to believe he possessed anatomical knowledge.</p>
<p>The case generated an unprecedented media frenzy. Letters purporting to be from the killer were sent to newspapers and police, including the infamous "From Hell" letter accompanied by half a human kidney.</p>`,
    image: 'https://images.unsplash.com/photo-1461360228754-6e81c478b882?w=1200&h=800&fit=crop',
    category: categories[3],
    author: authors[1],
    publishedAt: '2024-03-25',
    readingTime: 11,
    featured: false,
    trending: true,
    tags: ['jack-the-ripper', 'london', 'victorian', 'historical'],
  },
  {
    id: '6',
    slug: 'dyatlov-pass-incident',
    title: 'Death on Dyatlov Pass: The Night Nine Hikers Never Returned',
    excerpt: 'In 1959, nine experienced hikers died under inexplicable circumstances in the Ural Mountains. Six decades later, theories abound.',
    content: `<p>On February 2, 1959, nine young hikers set up camp on the slopes of Kholat Syakhl — a mountain in the northern Urals whose indigenous name translates ominously to "Dead Mountain." They were experienced, well-equipped, and in good spirits. None of them would survive the night.</p>
<p>When a search party finally reached their campsite weeks later, they found the tent had been slashed open from the inside. The hikers had fled into the freezing darkness wearing little more than their undergarments. Temperatures that night dropped to minus 30 degrees Celsius.</p>
<p>The bodies were found scattered across the mountainside over the following months. Some had died of hypothermia, as expected. But others bore injuries that defied explanation — massive chest trauma consistent with the force of a car crash, a missing tongue, and signs of exposure to radioactive contamination.</p>`,
    image: 'https://images.unsplash.com/photo-1504701954957-2010ec3bcec1?w=1200&h=800&fit=crop',
    category: categories[5],
    author: authors[2],
    publishedAt: '2024-04-10',
    readingTime: 13,
    featured: false,
    trending: false,
    tags: ['dyatlov', 'russia', 'mystery', 'hiking'],
  },
  {
    id: '7',
    slug: 'db-cooper-skyjacking-mystery',
    title: 'D.B. Cooper: The Man Who Vanished Into the Storm',
    excerpt: 'In 1971, a man hijacked a plane, collected $200,000 in ransom, and parachuted into the night. He was never found.',
    content: `<p>On the afternoon of November 24, 1971, a man calling himself Dan Cooper boarded Northwest Orient Airlines Flight 305 in Portland, Oregon. He was dressed in a business suit, carrying a briefcase. He ordered a bourbon and soda, lit a cigarette, and handed the flight attendant a note.</p>
<p>The note informed her he had a bomb. His demands were simple: $200,000 in cash and four parachutes, delivered upon landing in Seattle. The airline complied. After the passengers were released and the ransom delivered, Cooper directed the crew to take off again, heading for Mexico City.</p>
<p>Somewhere over the dense forests of southwestern Washington, in the middle of a raging thunderstorm, D.B. Cooper lowered the rear staircase of the Boeing 727 and jumped into the night with 21 pounds of cash strapped to his body. He was never seen again.</p>`,
    image: 'https://images.unsplash.com/photo-1478760329108-5c3ed9d495a0?w=1200&h=800&fit=crop',
    category: categories[4],
    author: authors[0],
    publishedAt: '2024-04-28',
    readingTime: 9,
    featured: false,
    trending: true,
    tags: ['db-cooper', 'hijacking', 'fbi', 'unsolved'],
  },
  {
    id: '8',
    slug: 'alcatraz-escape-1962',
    title: 'The Great Escape from Alcatraz: Did They Survive?',
    excerpt: 'In June 1962, three inmates vanished from the most secure prison in America. The FBI says they drowned. Others aren\'t so sure.',
    content: `<p>Alcatraz Federal Penitentiary sat on a rocky island in the middle of San Francisco Bay, surrounded by frigid waters and treacherous currents. It was designed to be escape-proof. For 29 years, it was. Until the night of June 11, 1962.</p>
<p>Frank Morris and brothers John and Clarence Anglin had spent months preparing. Using sharpened spoons and a makeshift drill fashioned from a stolen vacuum cleaner motor, they chipped away at the deteriorating concrete around ventilation ducts in their cells. They crafted remarkably lifelike dummy heads from soap, toilet paper, and real hair gathered from the prison barbershop.</p>
<p>On that June night, the three men squeezed through the widened vents, climbed to the roof, descended down a drainpipe, and reached the shore. Using a raft made from over 50 stolen raincoats, they launched into the bay and vanished into the fog.</p>`,
    image: 'https://images.unsplash.com/photo-1453873531674-2151bcd01707?w=1200&h=800&fit=crop',
    category: categories[3],
    author: authors[1],
    publishedAt: '2024-05-15',
    readingTime: 11,
    featured: false,
    trending: false,
    tags: ['alcatraz', 'prison-escape', 'san-francisco'],
  },
  {
    id: '9',
    slug: 'jonbenet-ramsey-christmas-night',
    title: 'JonBenét Ramsey: The Christmas Night That Shattered a Family',
    excerpt: 'The 1996 murder of a six-year-old beauty queen in Boulder, Colorado, remains one of America\'s most heartbreaking unsolved cases.',
    content: `<p>On the morning of December 26, 1996, Patsy Ramsey descended the spiral staircase of her family's Boulder, Colorado home to find a two-and-a-half-page ransom note on the stairs. Her six-year-old daughter, JonBenét, was missing from her bedroom.</p>
<p>The ransom note demanded $118,000 — curiously close to the amount of John Ramsey's recent bonus — and warned against contacting police. Despite this warning, the Ramseys called 911 immediately. Hours later, John Ramsey himself found JonBenét's body in a basement room of the house.</p>
<p>What followed was a case that divided a nation, destroyed a family's reputation, and exposed deep flaws in the Boulder Police Department's investigation. The crime scene was contaminated almost immediately, with friends and family walking through the house before investigators could process it.</p>`,
    image: 'https://images.unsplash.com/photo-1509248961406-689e1e7de57d?w=1200&h=800&fit=crop',
    category: categories[1],
    author: authors[2],
    publishedAt: '2024-06-02',
    readingTime: 16,
    featured: false,
    trending: false,
    tags: ['jonbenet', 'boulder', 'cold-case'],
  },
  {
    id: '10',
    slug: 'bermuda-triangle-flight-19',
    title: 'Flight 19: The Patrol That Flew Into Oblivion',
    excerpt: 'Five Navy torpedo bombers vanished over the Bermuda Triangle in 1945. The rescue plane sent after them disappeared too.',
    content: `<p>At 2:10 PM on December 5, 1945, five TBM Avenger torpedo bombers lifted off from Fort Lauderdale Naval Air Station on a routine training mission designated Flight 19. The squadron of 14 airmen was led by Lieutenant Charles Taylor, an experienced pilot with over 2,500 flight hours.</p>
<p>The mission was simple: fly east, conduct practice bombing runs, then return to base. The entire exercise was expected to take about two hours. Instead, it became the most famous disappearance in Bermuda Triangle lore.</p>
<p>About 90 minutes into the flight, Taylor radioed the tower with a disturbing message: "We seem to be off course. We cannot see land." His compasses, he reported, were malfunctioning. Both of them. The squadron began flying in circles over the open ocean as fuel dwindled and daylight faded.</p>`,
    image: 'https://images.unsplash.com/photo-1516557070061-c3d1653fa646?w=1200&h=800&fit=crop',
    category: categories[4],
    author: authors[0],
    publishedAt: '2024-06-20',
    readingTime: 10,
    featured: false,
    trending: false,
    tags: ['bermuda-triangle', 'aviation', 'military'],
  },
  {
    id: '11',
    slug: 'ted-bundy-mask-of-normalcy',
    title: 'Ted Bundy: The Charming Monster Next Door',
    excerpt: 'He was handsome, articulate, and studying law. He was also one of the most prolific serial killers in American history.',
    content: `<p>Ted Bundy defied every expectation of what a serial killer should look like. He was handsome, well-spoken, and charismatic. He volunteered at a suicide prevention hotline. He was studying law. He was, by all outward appearances, the ideal young American man.</p>
<p>Behind that carefully constructed mask of normalcy lurked something monstrous. Between 1974 and 1978, Bundy murdered at least 30 young women across seven states, though the true number may never be known. He confessed to 30 homicides in the days before his execution, but investigators believe the actual count could be significantly higher.</p>`,
    image: 'https://images.unsplash.com/photo-1478760329108-5c3ed9d495a0?w=1200&h=800&fit=crop',
    category: categories[0],
    author: authors[2],
    publishedAt: '2024-07-05',
    readingTime: 14,
    featured: false,
    trending: true,
    tags: ['bundy', 'serial-killer', 'psychology'],
  },
  {
    id: '12',
    slug: 'madeleine-mccann-vanishing',
    title: 'The Vanishing of Madeleine McCann: A Parents\' Endless Nightmare',
    excerpt: 'A three-year-old girl disappeared from a Portuguese holiday apartment in 2007. The search spans continents and continues to this day.',
    content: `<p>On the evening of May 3, 2007, Kate and Gerry McCann left their three children sleeping in their ground-floor holiday apartment in Praia da Luz, Portugal, while they dined at a tapas restaurant approximately 55 meters away. They and their friends took turns checking on the children throughout the evening.</p>
<p>At approximately 10 PM, Kate McCann returned to the apartment to find the bedroom window open and three-year-old Madeleine missing from her bed. The alarm was raised immediately, but despite a massive search operation, Madeleine was nowhere to be found.</p>`,
    image: 'https://images.unsplash.com/photo-1504701954957-2010ec3bcec1?w=1200&h=800&fit=crop',
    category: categories[2],
    author: authors[0],
    publishedAt: '2024-07-22',
    readingTime: 12,
    featured: false,
    trending: false,
    tags: ['mccann', 'portugal', 'missing-child'],
  },
  {
    id: '13',
    slug: 'hinterkaifeck-farm-murders',
    title: 'Hinterkaifeck: The Farmstead Massacre That Haunts Germany',
    excerpt: 'In 1922, six people were murdered on an isolated Bavarian farm. The killer lived among the bodies for days. The case is still open.',
    content: `<p>In the days before the bodies were discovered, farmer Andreas Gruber told neighbors about strange things happening at Hinterkaifeck. He had found unfamiliar footprints in the snow leading from the edge of the forest to the farm — but none leading back. He heard footsteps in the attic. A newspaper appeared that no one in the family had purchased. The previous maid had quit months earlier, claiming the house was haunted.</p>
<p>On the evening of March 31, 1922, the entire Gruber family — Andreas, his wife Cäzilia, their widowed daughter Viktoria, her two children, and the newly arrived maid — were lured one by one to the barn, where they were killed with a mattock.</p>`,
    image: 'https://images.unsplash.com/photo-1461360228754-6e81c478b882?w=1200&h=800&fit=crop',
    category: categories[1],
    author: authors[1],
    publishedAt: '2024-08-10',
    readingTime: 9,
    featured: false,
    trending: false,
    tags: ['hinterkaifeck', 'germany', 'historical', 'cold-case'],
  },
];
